language: perl 
perl:
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"

matrix:
  include:
    - os: linux
      dist: trusty
      compiler: clang
      env:
       - MY_OS=trusty
    - os: linux
      dist: precise
      compiler: gcc
      env:
       - MY_OS=precise
    - os: osx
      osx_image: xcode7.2
      env:
       - MY_OS=macos

addons:
 apt:
  packages:
   - libmarc-record-perl
   - make

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install pkg-config yaz; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./test/travis/travis-init.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -yq libyaz5-dev; fi

before_script:
 - perl Makefile.PL

script:
 - make
 - make test
 - make install

